language: r
sudo: false
cache: packages
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
    env: DRAT_DEPLOY=true
  - os: osx
    osx_image: xcode9.4
  - os: osx
    osx_image: xcode11
    r_build_args: "--no-build-vignettes"
    r_check_args: "--ignore-vignettes --no-examples"
r_packages:
- covr
- drat
r_github_packages:
- cloudyr/travisci
after_success:
- R -q -e 'library("covr");codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test
  $DRAT_DEPLOY == "true" && bash drat.sh
- R -q -e "travisci::restart_last_build('cloudyr/awspack')"
env:
  global:
    secure: kLDGA4nZ0TxupjkKbN8rDkzeqSCC1MmHn18H97bGYhg+isJoaHstD1pvpymbL4WegtdNwUA+Rd4q/MQf888bCrn2flCEadcqxWZXTqyGP8f5mKIrpOtUijvz/XJU9Xx7OO81jqWUC6hDQLM7MXw5Hz0/USQTr3mSFmyjwEPJ64afdKWFASrSEMdyTy3ngTGOMF74hy2PPpGf7n7e4BzA346tUDj6WnPPGkDQZb/fREAISBcjiIDov2wK9GtWwH9xNeGDCyxj9Lbt6F6rD+ILplTskhVkyhXQGuATXgcoqLSBzRkkGvl0o3VuYMt+r7hHzh1HM/t+IZyvdUPV7DMaFe1I+ODc5KECNEA5HyOcTgatdH4AzeLO7lm5YgOuycxKnHyWRRjQ3iyWrjphW+K1GK3XxK32Hab3llgFOZBEwJVBCn2ZaNNHzE0Y8Th4RF6gyH7R68I0PKu+K80m+K4LA7MKX/pM3s+Md+OISOZ742XdzRRaZjKpAH4/v81IDq8F21a+jqgh5yXzZTFDwU2r49lC3oO1RKbpitqchP0L3B/jwDJ3VFdNUy07FCwSZwcNSKjIkkgs/9BfKvlNYf9i0nRJ3sNRf8OOSXH4DPw4l6gPCglfw6M8aP68cbW8I5VvKYSZ9Ks7gy0f4stXbjZG0ygnsEpDYZoKyeup8wiO9rA=
